### ISSUE TITLE
アプリケーションアーキテクチャのドキュメントにセキュリティ方針を追記する

### ISSUE THREAD

**Issue by tsuna-can-se** [AlesInfiny/maia#529]
# 概要

セキュリティ上考慮すべきポイント、方針を記載する。
セッションフィクセーション、CSRF対策など。
SQLインジェクションなど、システム形態にとらわれない.NETの方針は概要編へ、それ以外はシステム形態別のドキュメントに記載するイメージ。
何をどうするか、サンプルコードにどう反映するか、完了条件を検討するところから始める。

# 完了条件

- [ ] [ドキュメントの「アプリケーションアーキテクチャ」直下に 「セキュリティ編」カテゴリを作成し「クロスサイトスクリプティング」を追加する · Issue #950 · AlesInfiny/maia](https://github.com/AlesInfiny/maia/issues/950)
- [ ] [ドキュメント「セキュリティ編」カテゴリに「CSRF（クロスサイトリクエストフォージェリ）」を追加する · Issue #951 · AlesInfiny/maia](https://github.com/AlesInfiny/maia/issues/951)
- [ ] [ドキュメント「セキュリティ編」カテゴリに「SQLインジェクション」を追加する · Issue #952 · AlesInfiny/maia](https://github.com/AlesInfiny/maia/issues/952)
- [ ] [ドキュメント「セキュリティ編」カテゴリに「HTTPレスポンス分割」を追加する · Issue #953 · AlesInfiny/maia](https://github.com/AlesInfiny/maia/issues/953)
- [ ] [ドキュメント「セキュリティ編」カテゴリに「セッションフィクセイション／セッションハイジャック」を追加する · Issue #954 · AlesInfiny/maia](https://github.com/AlesInfiny/maia/issues/954)
- [ ] [ドキュメント「セキュリティ編」カテゴリに「evalインジェクション」を追加する · Issue #955 · AlesInfiny/maia](https://github.com/AlesInfiny/maia/issues/955)
- [ ] [ドキュメント「セキュリティ編」カテゴリに「クリックジャッキング」を追加する · Issue #956 · AlesInfiny/maia](https://github.com/AlesInfiny/maia/issues/956)
- [ ] [ドキュメントの「ガイド」直下に 「セキュアコーディングガイド」カテゴリを作成し「クライアントからの入力値を信頼しない」を追加する · Issue #957 · AlesInfiny/maia](https://github.com/AlesInfiny/maia/issues/957)
